"""add user and menu_services

Revision ID: fe4497a3afbf
Revises: a4f971cbdb8a
Create Date: 2025-11-16 09:57:38.178814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4497a3afbf'
down_revision: Union[str, Sequence[str], None] = 'a4f971cbdb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='パスワードハッシュ'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False, comment='ユーザーロール（admin/user）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.add_column('resources', sa.Column('menu_services', sa.JSON(), nullable=True, comment='メニュー・サービス情報（例: [{"name": "カット", "price": 3000}, ...]）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'menu_services')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
